// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuwclZbfFJumo7s_6i3TizdvjQb-uctPI',
    appId: '1:1017641780052:web:2f95558f25c36f54853ec1',
    messagingSenderId: '1017641780052',
    projectId: 'mynotes-eup-flutter-project',
    authDomain: 'mynotes-eup-flutter-project.firebaseapp.com',
    storageBucket: 'mynotes-eup-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBIcW5aik0jDLq3a9ZJWGXonfb4X0mU1I',
    appId: '1:1017641780052:android:8346e861c450f925853ec1',
    messagingSenderId: '1017641780052',
    projectId: 'mynotes-eup-flutter-project',
    storageBucket: 'mynotes-eup-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-TWMZjHwictW-sFBkZ3N3qoTYMTg-tfI',
    appId: '1:1017641780052:ios:079b808e9e01871c853ec1',
    messagingSenderId: '1017641780052',
    projectId: 'mynotes-eup-flutter-project',
    storageBucket: 'mynotes-eup-flutter-project.appspot.com',
    iosClientId: '1017641780052-85lc386h4jbvn6huhcg1vglig6ulqjnj.apps.googleusercontent.com',
    iosBundleId: 'com.dev.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-TWMZjHwictW-sFBkZ3N3qoTYMTg-tfI',
    appId: '1:1017641780052:ios:079b808e9e01871c853ec1',
    messagingSenderId: '1017641780052',
    projectId: 'mynotes-eup-flutter-project',
    storageBucket: 'mynotes-eup-flutter-project.appspot.com',
    iosClientId: '1017641780052-85lc386h4jbvn6huhcg1vglig6ulqjnj.apps.googleusercontent.com',
    iosBundleId: 'com.dev.mynotes',
  );
}
